"""Update the MTB section INSIDE the 'Activities — Hikes, Runs & MTB' tab, in place.

The MTB rides were moved out of standalone tabs into the Activities tab (under the
'🚵 MOUNTAIN BIKING — Colorado' header). This script rewrites ONLY that section
(Boulder + Steamboat + Crested Butte blocks) and preserves every row above it
(backpacking / day hikes / trail runs / Tahoe / Mammoth).

Run this to regenerate the MTB section after editing any ride data below.
"""
import gspread
from config import SPREADSHEET_ID, CREDENTIALS_FILE
from google.oauth2.service_account import Credentials
from mtb_tab import build_activities_mtb

creds = Credentials.from_service_account_file(
    CREDENTIALS_FILE,
    scopes=['https://www.googleapis.com/auth/spreadsheets'],
)
gc = gspread.authorize(creds)
sh = gc.open_by_key(SPREADSHEET_ID)

ACTIVITIES_TAB = "Activities — Hikes, Runs & MTB"
MASTER_HEADER = "🚵 MOUNTAIN BIKING — Colorado + Eastern Sierra  (consolidated from the MTB tabs)"

# ── BOULDER ─────────────────────────────────────────────────────────────────
boulder = {
    "title": "BOULDER MTB RIDES — Consolidated  (Jul 22–31)",
    "banner_text": ('⚠️ WATCH OUT: Boulder County "Alternating Trail Use Pilot" may BAN BIKES on certain '
                    'days at HEIL VALLEY RANCH, HALL RANCH & BETASSO during the trip (late Jul 2026). '
                    'Status as of 2026-05-31: proposed, decision pending. Re-check before locking ride days → '
                    'bouldercounty.gov pilot page'),
    "banner_url": "https://bouldercounty.gov/open-space/management/alternating-trail-use/",
    "col8_header": "Access / Day Rules",
    "origin": "582 Locust Pl, Boulder, CO",
    "rides": [
        ["Walker Ranch Loop", "Best descent in the area; marquee technical day",
         "7.8 mi loop", "~1,510 ft", "Walker Ranch TH (Flagstaff Rd)",
         "~25 min W", "🔴 Black", "Open daily",
         "Meyers Homestead Trail (same lot, dog hike)", "✅ Leash"],
        ["Hall Ranch — Bitterbrush → Nelson Loop", "Marquee intermediate destination",
         "~12 mi RT", "~1,500–1,800 ft", "Bitterbrush lot, CO-7 (Lyons)",
         "~30–35 min N", "🔵→🔴 (Lower Bitterbrush rock garden)", "⚠️ Pilot risk — verify",
         "Nighthawk Trail (hiking-only, leash)", "✅ Leash"],
        ["Hall Ranch via Antelope", "Mellower line — skip the rock-garden grind",
         "~10 mi RT", "~1,200 ft", "Antelope TH, CO-7 (Lyons)",
         "~33 min N", "🔵 Blue", "⚠️ Pilot risk — verify",
         "Nighthawk Trail; Rabbit Mtn", "✅ Leash"],
        ["Heil Valley Ranch — Wapiti / Ponderosa", "Stellar intermediate; Corral-side classic",
         "~7.5 mi", "~900 ft", "Corral TH",
         "~20–25 min N", "🔵 Blue", "⚠️ Pilot risk — verify",
         "Rabbit Mtn / Hall Nighthawk (Heil = no dogs)", "❌ NO DOGS"],
        ["Heil — Picture Rock (Lyons side)", "Longer loop up to Wild Turkey / Ponderosa",
         "~12–15 mi RT", "~1,400 ft", "Picture Rock TH (Lyons)",
         "~30 min N", "🔵 Blue", "⚠️ Pilot risk — verify",
         "Rabbit Mtn (Heil = no dogs)", "❌ NO DOGS"],
        ["Betasso Preserve — Canyon + Benjamin", "Quick close-to-town intermediate",
         "7.4 mi", "~830 ft", "Betasso TH (Sugarloaf Rd)",
         "~20 min W", "🔵 Blue (directional / one-way)", "⚠️ Closed to bikes WED + SAT (+ pilot risk)",
         "Betasso Canyon Loop on foot; Boulder Falls", "✅ Leash"],
        ["Marshall Mesa / Doudy Draw / Flatirons Vista", "Smooth XC; beginner-friendly",
         "12.6 mi loop (shorter opts)", "~975 ft", "Marshall Mesa TH (Hwy 93)",
         "~15 min S", "🟢 / 🔵 (Coal Seam 🔴)", "Open daily",
         "Doudy Draw / Spring Brook + Flatirons Vista", "✅ OSMP voice-&-sight off-leash; else leash"],
        ["Dirty Bismark loop", "Mellowest big-mileage day; dog-friendly, gravel-bike-able",
         "~15 mi", "~700 ft", "Marshall Mesa TH (Hwy 93)",
         "~15 min S", "🟢 Green", "Open daily",
         "Doudy Draw / Community Ditch", "✅ OSMP voice-&-sight off-leash"],
        ["Magnolia — West / East Mag", "Prime late-July (dries out late); XC maze",
         "10–15 mi network (85 trails)", "~1,000+ ft", "West Magnolia TH (FSR 355)",
         "~30–35 min W", "🔵 Blue XC", "Open daily (USFS land)",
         "West Mag forest roads; Nederland trails", "✅ OFF-LEASH (USFS)"],
        ["Boulder Valley Ranch / Reservoir (incl. North Sky Trail)",
         "Beginner warm-up; flattest; North Sky = newest & mellow",
         "~8–10 mi", "~300–400 ft", "Boulder Valley Ranch / Eagle TH",
         "~10–12 min NE", "🟢 Green (Hidden Valley 🔵)", "Open daily (dogs banned on North Sky itself)",
         "Wonderland Lake; Reservoir off-leash dog swim", "✅ Leash (North Sky = no dogs)"],
        ["Valmont Bike Park", "Skills / jumps / pump-track practice",
         "n/a (15 trails)", "n/a", "In-town — 3160 Airport Rd",
         "~10 min E", "🟢→⚫ all levels", "Open daily",
         "Boulder Creek Path", "✅ Leash"],
    ],
    "queries": [
        "Walker Ranch Trailhead, Flagstaff Road, Boulder, CO",
        "Hall Ranch Trailhead, Lyons, CO",
        "Antelope Trailhead, Hall Ranch, Lyons, CO",
        "Heil Valley Ranch Corral Trailhead, Boulder, CO",
        "Picture Rock Trailhead, Lyons, CO",
        "Betasso Preserve Trailhead, Boulder, CO",
        "Marshall Mesa Trailhead, Boulder, CO",
        "Marshall Mesa Trailhead, Boulder, CO",
        "West Magnolia Trailhead, Nederland, CO",
        "Boulder Valley Ranch Trailhead, Boulder, CO",
        "Valmont Bike Park, Boulder, CO",
    ],
    "trailforks": [
        "https://www.trailforks.com/trails/walker-ranch-loop/",
        "https://www.trailforks.com/region/hall-ranch-15771/",
        "https://www.trailforks.com/region/hall-ranch-15771/",
        "https://www.trailforks.com/region/heil-valley-ranch-15770/",
        "https://www.trailforks.com/region/heil-valley-ranch-15770/",
        "https://www.trailforks.com/region/betasso-preserve/",
        "https://www.trailforks.com/region/marshall-mesa-doudy-draw-flatirons-vista/",
        "https://www.trailforks.com/region/marshall-mesa-doudy-draw-flatirons-vista/",
        "https://www.trailforks.com/region/magnolia-20800/",
        "https://www.trailforks.com/region/boulder-valley-ranch--boulder-reservoir/",
        "https://www.trailforks.com/region/valmont-bike-park/",
    ],
    "hype": ["🌟 MUST-RIDE", "🌟 MUST-RIDE", "⭐ Highly rated", "🌟 MUST-RIDE", "⭐ Highly rated",
             "⭐ Highly rated", "⭐ Highly rated", "", "⭐ Highly rated", "", "⭐ Highly rated"],
    "must_do": {"Walker Ranch Loop", "Marshall Mesa / Doudy Draw / Flatirons Vista",
                "Magnolia — West / East Mag"},
}

# ── STEAMBOAT ───────────────────────────────────────────────────────────────
steamboat = {
    "title": "STEAMBOAT MTB RIDES — Consolidated  (Aug 2–6)",
    "banner_text": ("🚐 Buffalo Pass rides (Flash of Gold, Grouse Ridge, Divide) have NO commercial shuttle — "
                    "self-shuttle or ride the loop back to town. Emerald Mtn & Spring Creek are rideable straight "
                    "from downtown. Bike Park = gondola + Christie Peak Express, ~$50–70/day (Ikon = 2 free days). "
                    "Altitude 6,900–10,000 ft: ease in day 1, afternoon thunderstorms common — ride early."),
    "banner_url": None,
    "col8_header": "Shuttle",
    "origin": "1036 Lincoln Ave, Steamboat Springs, CO",
    "rides": [
        ["Flash of Gold → Spring Roll → Spring Creek", "Headline enduro day; the no-shuttle loop back to town",
         "~19 mi loop", "~2,300 ft", "Dry Lake / Buffalo Pass Rd",
         "~25–30 min NE", "🔴 Black (loop overall int–adv)", "Self-shuttle or ride the loop (no commercial)",
         "Mad Creek / Hot Springs Trail", "✅ Off-leash (Nat'l Forest)"],
        ["Grouse Ridge (Buffalo Pass)", "The descent prize — ~1,687 ft down in 3 mi",
         "~3 mi descent (≈15 mi w/ Flash of Gold)", "~1,700 ft descent", "Buffalo Pass / Summit Lake",
         "~30 min NE", "🔵 Blue", "Self-shuttle (pairs w/ Flash of Gold)",
         "Fish Creek Falls", "✅ Off-leash (Nat'l Forest)"],
        ["Emerald Mountain Loops (Beall / Ridge / Rotary + NPR)", "Town warm-up; pedal straight from downtown",
         "~13–16 mi", "~2,170 ft", "Howelsen Hill / 5th St",
         "walkable / ~5 min", "🔵 Blue (NPR & Rotary 🟢)", "None — loop from town",
         "Emerald Blackmere / Lupine hikes (same hill)", "✅ Yes (off-leash zones)"],
        ["Spring Creek + Spring Roll", "Early-season staple (dries first); downhill-only Spring Roll option",
         "10.4 mi", "~1,000 ft", "Amethyst Dr / Maple St (1 mi from town)",
         "~5 min", "🔵 Blue (int–adv)", "None",
         "Spring Creek Trail (same corridor)", "✅ Yes"],
        ["Mad Creek / Red Dirt Loop", "Short, technical, tight singletrack",
         "~10 mi", "~1,500 ft", "Mad Creek TH (CR-129)",
         "~12 min N", "🔴 Black (technical)", "None — loop",
         "Mad Creek / Red Dirt (both dog hikes)", "✅ Off-leash (Nat'l Forest)"],
        ["The Divide Trail (Wyoming / CDT #1101)", "Big high-alpine classic; roots, rocks, flow",
         "~26 mi", "~2,000 ft", "Dumont Lake / Rabbit Ears Pass",
         "~30 min SE", "🔴 Black (advanced)", "Point-to-point self-shuttle option",
         "Rabbit Ears Peak", "✅ Off-leash (Nat'l Forest)"],
        ["Buffalo Pass / Long Lake Loop", "Easy big-view alpine — mellow Anny + dog day",
         "14 mi", "~800 ft", "Buffalo Pass Rd",
         "~30 min NE", "🟢 Green", "None — loop",
         "Fish Creek Falls", "✅ Off-leash (Nat'l Forest)"],
        ["Panorama + Fiddlehead", "Family / easy; Yampa Valley + Flat Tops views",
         "~3–5 mi", "~300 ft", "Buffalo Pass area (~6 mi out)",
         "~15 min", "🟢 Green", "None",
         "Yampa River Core Trail", "✅ Yes"],
        ["Steamboat Bike Park", "Lift-served skills / DH; green→black, family-friendly",
         "n/a (15 trails)", "2,200 ft vert (lift)", "Steamboat Resort base (gondola + Christie Peak Express)",
         "~5 min", "🟢→🔴 (Cowpoke 🟢 … Buckin' Bronc 🔴)", "Lift-served",
         "Yampa River Core Trail", "✅ Leash (base area)"],
    ],
    "queries": [
        "Dry Lake Trailhead, Buffalo Pass Road, Steamboat Springs, CO",
        "Summit Lake, Buffalo Pass, Steamboat Springs, CO",
        "Howelsen Hill, Steamboat Springs, CO",
        "Spring Creek Trailhead, Amethyst Drive, Steamboat Springs, CO",
        "Mad Creek Trailhead, Steamboat Springs, CO",
        "Dumont Lake Trailhead, Rabbit Ears Pass, Steamboat Springs, CO",
        "Summit Lake, Buffalo Pass, Steamboat Springs, CO",
        "Buffalo Pass Road, Steamboat Springs, CO",
        "Steamboat Resort, Steamboat Springs, CO",
    ],
    "trailforks": [
        "https://www.trailforks.com/trails/flash-of-gold/",
        "https://www.trailforks.com/trails/grouse-93808/",
        "https://www.trailforks.com/region/emerald-mountain/",
        "https://www.trailforks.com/trails/spring-roll-227917/",
        "https://www.trailforks.com/region/mad-creek/",
        "https://www.trailforks.com/trails/cdt-wyoming-trail-12517/",
        "https://www.trailforks.com/region/buffalo-pass/",
        "https://www.trailforks.com/trails/panorama-94044/",
        "https://www.trailforks.com/region/steamboat-bike-park/",
    ],
    "hype": ["🌟 MUST-RIDE", "⭐ Highly rated", "⭐ Highly rated", "⭐ Highly rated", "",
             "⭐ Highly rated", "", "", "⭐ Highly rated"],
    "must_do": {"Flash of Gold → Spring Roll → Spring Creek", "Grouse Ridge (Buffalo Pass)",
                "Emerald Mountain Loops (Beall / Ridge / Rotary + NPR)", "Spring Creek + Spring Roll"},
}

# ── CRESTED BUTTE ───────────────────────────────────────────────────────────
crested_butte = {
    "title": "CRESTED BUTTE MTB RIDES — Consolidated  (Aug 7–12)",
    "banner_text": ("🚐 Doctor Park needs a shuttle (Dolly's Mountain Shuttle — see 'MTB Shuttles & Guides' tab; "
                    "book ahead). Trail 401 also rides as a no-shuttle Gothic Rd loop (~25 mi / 4k vert). Strand Hill "
                    "is the gentlest 'big' ride — good day-1 acclimatization. ⚠️ Baxter→Green Lake is bear country, NO dogs. "
                    "Base elev 9,400 ft (town 8,900) — altitude is real; ride early, watch afternoon storms."),
    "banner_url": None,
    "col8_header": "Shuttle",
    "origin": "6 Emmons Rd, Mount Crested Butte, CO",
    "rides": [
        ["Doctor Park", "Consensus #1 — best descent in CB",
         "~16–19 mi (9 mi trail)", "~2,600 ft / -2,558 ft", "Harmels / Spring Creek Rd",
         "~35–40 min S (shuttle)", "🔴 Black", "✅ Yes (Dolly's or self)",
         "Copper Creek / Judd Falls", "✅ Yes"],
        ["Trail 401 (Gothic Rd loop)", "Iconic wildflower singletrack; pedal up from base",
         "~14 mi loop (~25 mi from town)", "~1,500–3,000 ft", "Schofield Pass / Gothic Rd (Judd Falls)",
         "~15 min N (or ride up)", "🔵→🔴 (int–adv)", "Optional (Dolly's) or ride Gothic Rd up",
         "Judd Falls / Copper Creek", "✅ Yes"],
        ["Teocalli (Teo) Ridge", "2k climb / 2k descent epic; no shuttle",
         "~11 mi", "~2,730 ft", "Brush Creek Rd / East River",
         "~15 min SE", "🔴 Black", "No — earn the climb",
         "Three Lakes Loop / Brush Creek", "✅ Yes"],
        ["Reno – Flag – Bear – Deadman", "4 trails, 3 climbs, 3 descents — classic loop",
         "~18 mi", "~1,800–2,400 ft", "Deadman's Gulch TH (Cement Creek Rd)",
         "~20 min S", "🔴 Black", "No — loop",
         "Cement Creek area", "✅ Yes"],
        ["Strand Hill", "Gentlest 'big' ride — day-1 acclimatization pick",
         "~6–7 mi", "~1,000–1,900 ft", "Brush Creek Rd / East River",
         "~15 min SE", "🔵→🔴", "No",
         "Brush Creek", "✅ Yes"],
        ["Snodgrass", "Wildflower flow; very accessible, close to base",
         "~4 mi (14-mi loop opt)", "~600–1,000 ft", "Gothic Rd / Washington Gulch Rd",
         "~8 min N", "🔵 Blue (intermediate)", "No",
         "Snodgrass hiking trail (same)", "✅ Yes (leash near wildlife)"],
        ["Lupine", "Smooth beginner/int; valley views — Anny + dog",
         "~4–5 mi", "~300–610 ft", "Lower Loop / Lupine TH",
         "~10 min (in town)", "🔵 Blue (beg–int)", "No",
         "Lower Loop / Woods Walk", "✅ Yes"],
        ["Lower Loop / Woods Walk (town trails)", "Beginner + dog-friendly town classic",
         "4.5–9 mi", "~650 ft", "Peanut Lake Rd / Woods Walk (CB town)",
         "~10 min (down in town)", "🟢 Green / easy", "No",
         "Woods Walk / Lower Loop (dog hikes)", "✅ Yes"],
        ["Mt-CB base trails (Painter Boy / Columbine / Up & Away / Teddy's)", "Warm-up right outside the door",
         "2–4 mi", "minimal", "CBMR base (Mt Crested Butte)",
         "walkable / ~2 min", "🟢 Green", "No",
         "Woods Walk", "✅ Yes"],
        ["Baxter Gulch → Green Lake", "Long in-town backcountry loop; alpine lake",
         "~15–17 mi", "~2,800 ft", "Baxter Gulch TH (downtown CB)",
         "~10 min (in town)", "🔵→🔴", "No — loop",
         "Lower Loop", "❌ No (bear country)"],
        ["Dyke Trail", "Kebler Pass aspens; epic in fall",
         "5–6 mi", "~500–1,000 ft", "Horse Ranch Park (Kebler Pass Rd)",
         "~20 min W", "🔵 Blue (int–adv)", "No",
         "Three Lakes Loop (Kebler Pass)", "✅ Off-leash (Nat'l Forest)"],
        ["Evolution Bike Park", "Lift-served DH / enduro — world-class",
         "n/a (54 trails)", "lift vert", "CBMR base (Mt Crested Butte)",
         "walkable / ~2 min", "🟢→⚫ (Psycho Rocks ⚫)", "Lift-served",
         "Woods Walk", "❌ No (bike park)"],
    ],
    "queries": [
        "Doctor Park Trailhead, Spring Creek Road, Almont, CO",
        "Judd Falls Trailhead, Gothic Road, Crested Butte, CO",
        "Brush Creek Trailhead, Crested Butte, CO",
        "Deadmans Gulch Trailhead, Cement Creek Road, Crested Butte, CO",
        "Strand Hill Trailhead, East River Road, Crested Butte, CO",
        "Snodgrass Trailhead, Gothic Road, Mount Crested Butte, CO",
        "Lupine Trailhead, Crested Butte, CO",
        "Lower Loop Trailhead, Peanut Lake Road, Crested Butte, CO",
        "Crested Butte Mountain Resort, Mount Crested Butte, CO",
        "Baxter Gulch Trailhead, Crested Butte, CO",
        "Horse Ranch Park Trailhead, Kebler Pass Road, Crested Butte, CO",
        "Evolution Bike Park, Mount Crested Butte, CO",
    ],
    "trailforks": [
        "https://www.trailforks.com/trails/dr-park/",
        "https://www.trailforks.com/trails/trail-401/",
        "https://www.trailforks.com/trails/teocalli-ridge/",
        "https://www.trailforks.com/trails/reno-ridge-78512/",
        "https://www.trailforks.com/trails/strand-hill-13488/",
        "https://www.trailforks.com/trails/snodgrass/",
        "https://www.trailforks.com/trails/lupine-13437/",
        "https://www.trailforks.com/trails/lower-loop/",
        "https://www.trailforks.com/trails/painter-boy/",
        "https://www.trailforks.com/trails/baxter-gulch/",
        "https://www.trailforks.com/trails/dyke-trail/",
        "https://www.trailforks.com/region/cbmr-evolution-bike-park/",
    ],
    "hype": ["🌟 MUST-RIDE", "🌟 MUST-RIDE", "🌟 MUST-RIDE", "⭐ Highly rated", "⭐ Highly rated",
             "⭐ Highly rated", "⭐ Highly rated", "⭐ Highly rated", "", "⭐ Highly rated",
             "⭐ Highly rated", "⭐ Highly rated"],
    "must_do": {"Doctor Park", "Trail 401 (Gothic Rd loop)", "Teocalli (Teo) Ridge",
                "Lower Loop / Woods Walk (town trails)"},
}

eastern_sierra = {
    "title": "EASTERN SIERRA MTB — Mammoth Lakes & June Lake  (Aug 14–18)",
    "banner_text": ("🚡 Mammoth Bike Park is the crown jewel — 80+ mi lift-served (Ikon Pass = free bike-park "
                    "tickets; confirm your tier). Best backcountry descent: Lower Rock Creek (~35 min S, "
                    "self-shuttle on the parallel road). June Mountain runs NO summer lifts — everything at "
                    "June Lake is pedal-up. 🐕 No dogs at the bike park; all the Nat'l-Forest XC rides are "
                    "dog-OK (leash where signed). Altitude is real: town 7,880 ft, summit 11,053 ft."),
    "banner_url": None,
    "col8_header": "Access",
    "origin": "Mammoth Lakes, CA",
    "rides": [
        ["Mammoth Mountain Bike Park", "The premier U.S. lift-served park — 80+ mi of berms, jumps, drops & pro lines on a volcano",
         "80+ mi; full lap ~5–15 mi", "~3,000 ft lift-served descent (summit ~11,053 ft)",
         "Main Lodge / The Village (Panorama Gondola + Discovery Chair)", "~10 min W (in town)",
         "⚫ All levels (🟢 Discovery → ⚫ Velociraptor)", "Lift-served (gondola + chair; park ticket — Ikon = free tickets)",
         "Panorama Gondola scenic ride + Top of the Sierra interpretive trail", "❌ No (bike park)"],
        ["Off the Top → Beach Cruiser → Downtown", "The marathon descent — summit to Village, the longest run in the park",
         "~15 mi pt-to-pt (Off the Top ~5.1 mi)", "~3,000 ft descent",
         "Top of Panorama Gondola (summit)", "~10 min W (in town)",
         "🔵 Blue (long, flowy)", "Lift-served (gondola; park ticket)",
         "Reds Lake area — lakeside picnic / swim on foot", "❌ No (bike park)"],
        ["Kamikaze (Eliminator DH)", "Ride the most famous descent in MTB history — fast, raw, brakes-off legend",
         "~3+ mi top-to-bottom", "~2,000+ ft descent",
         "Top of Panorama Gondola (summit)", "~10 min W (in town)",
         "🔴 Black (fast, rough — DH-friendly)", "Lift-served (gondola; park ticket)",
         "Top of the Sierra summit deck + interpretive walk", "❌ No (bike park)"],
        ["Lower Rock Creek Trail", "The Eastern Sierra's classic ~8 mi tech descent through a creekside aspen canyon",
         "~7.7 mi pt-to-pt", "~1,934 ft descent (≈30 ft climb)",
         "Upper Lower Rock Creek TH, Lower Rock Creek Rd (Tom's Place)", "~35 min S",
         "🔴 Black-ish (TF blue overall; lower gorge tech rock gardens)", "Self-shuttle (road parallels trail, 2 crossings) or 2-car / out-and-back",
         "Rock Creek Lake basin trails near Tom's Place (alpine, dog-friendly)", "✅ Off-leash (Nat'l Forest/BLM — leash where signed)"],
        ["Mammoth Rock Trail (Sherwin Ridge)", "Exposed ridge singletrack under Mammoth Rock — caldera views, aspens, a tech boulder field",
         "~5 mi RT (out-and-back)", "~600–865 ft climb",
         "Sherwin Creek Rd TH (Sherwin Meadows)", "~5 min S (edge of town)",
         "🔵 Blue (one tech boulder section)", "None — pedal up from town / Sherwin Creek Rd",
         "Sherwin Lakes Trail (~800 ft to alpine lakes — great hike + dog)", "✅ Off-leash (Nat'l Forest — leash courtesy)"],
        ["Uptown / Downtown Town Loop", "Mellow forested town singletrack — pedal Uptown, rip Mountain View/Downtown; no park pass",
         "~5 mi loop (extend to ~8–10)", "~550–1,000 ft climb",
         "The Village (Uptown TH, off Hwy 203)", "~5 min (in town)",
         "🔵 Blue (flowy XC)", "None — loop (or download from Main Lodge w/ Pedal Pass)",
         "Lakes Basin paved path / Horseshoe Lake Loop (flat, dog-friendly)", "✅ Off-leash (Nat'l Forest — leash near Village)"],
        ["Inyo Craters Loop", "Big pedally backcountry loop on dirt roads + singletrack past volcanic crater lakes",
         "~10.3 mi loop", "~1,000–1,200 ft",
         "Inyo Craters TH via Mammoth Scenic Loop (FS 3S30)", "~15 min N",
         "🔵→🔴 (int–adv; FS roads + singletrack)", "None — loop (pedal)",
         "Inyo Craters interpretive hike to the crater lakes (~0.6 mi, dog-friendly)", "✅ Off-leash (Nat'l Forest)"],
        ["Mammoth Knolls Loop", "Quiet near-town loop mixing FS roads with single/doubletrack — easy lap",
         "~10.8 mi loop", "~1,200 ft",
         "Mammoth Knolls (near The Village / Forest Trail)", "~5 min (in town)",
         "🔵 Blue (XC)", "None — loop (pedal)",
         "Knolls / Shady Rest Park trails (flat forest walking, dog-friendly)", "✅ Off-leash (Nat'l Forest)"],
        ["Reversed Peak Loop", "June Lake's standout — climb (some hike-a-bike) to a ridge above Silver Lake, then a tech aspen descent",
         "~2.8 mi loop", "~710 ft descent",
         "Reversed Peak / June Lake Loop (off Hwy 158 near Silver Lake)", "~30 min N",
         "🔴 Black (TF 'blue'; south end advanced tech)", "None — loop (pedal + hike-a-bike)",
         "Reversed Peak / Yost Lake Trail (alpine lakes, dog-friendly)", "✅ Off-leash (Nat'l Forest — leash courtesy)"],
        ["June Mountain 'Chair 6' Bike Trail", "Lung-buster fire-road climb up the ski hill to big views, then a fast rocky descent",
         "~8 mi out-and-back", "~2,200 ft climb",
         "Lakeview Dr, town of June Lake (Canyon Trail to June Mtn)", "~30 min N",
         "🔴 Black (sustained climb + rocky/sandy descent)", "Pedal up (June Mtn runs NO summer lifts)",
         "June Lake Loop lakeshore trails / Fern Lake Trail (dog-friendly)", "✅ Off-leash (Nat'l Forest)"],
    ],
    "queries": [
        "Mammoth Mountain Main Lodge, Minaret Road, Mammoth Lakes, CA",
        "Panorama Gondola, Mammoth Mountain, Mammoth Lakes, CA",
        "Mammoth Mountain Panorama Gondola, Mammoth Lakes, CA",
        "Lower Rock Creek Trailhead, Tom's Place, CA",
        "Sherwin Creek Road Trailhead, Mammoth Lakes, CA",
        "Uptown Trail Trailhead, The Village at Mammoth, Mammoth Lakes, CA",
        "Inyo Craters Trailhead, Mammoth Lakes, CA",
        "Mammoth Knolls Trailhead, Mammoth Lakes, CA",
        "Reversed Peak Trailhead, June Lake, CA",
        "June Mountain Ski Area, June Lake, CA",
    ],
    "trailforks": [
        "https://www.trailforks.com/region/mammoth-mountain-bike-park/",
        "https://www.trailforks.com/region/mammoth-mountain-bike-park/",
        "https://www.trailforks.com/region/mammoth-mountain-bike-park/",
        "https://www.trailforks.com/trails/lower-rock-creek/",
        "https://www.trailforks.com/region/mammoth-rock-56258/",
        "https://www.trailforks.com/route/uptown-beach-cruiser-mountain-view-loop/",
        "https://www.trailforks.com/region/mammoth-lakes/",
        "https://www.trailforks.com/region/mammoth-lakes/",
        "https://www.trailforks.com/trails/reversed-peak-loop-trail/",
        "https://www.trailforks.com/region/june-mountain-ski-area-68551/",
    ],
    "hype": ["🌟 MUST-RIDE", "⭐ Highly rated", "🌟 MUST-RIDE", "🌟 MUST-RIDE", "⭐ Highly rated",
             "", "", "", "⭐ Highly rated", ""],
    "must_do": {"Mammoth Mountain Bike Park", "Kamikaze (Eliminator DH)", "Lower Rock Creek Trail"},
}

build_activities_mtb(sh, ACTIVITIES_TAB, MASTER_HEADER, [boulder, steamboat, crested_butte, eastern_sierra])
print("All done.")
