"""
File writer for the image/PDF intake pipeline.

Flow: stage locally → copy to NAS → purge local.
Files are ALWAYS staged to ~/Documents/event-aggregator-intake/{file_id}/ first,
then copied to the NAS. Local staging is purged only after a successful NAS write.

If the NAS is offline, files stay staged locally and are flushed on the next run.

NAS path structure:
  {NAS_ROOT}/{category}/{subcategory}/{year}/{doc_type}/{date}_{slug}/
  e.g. /Volumes/Share1/Healthcare/0-Ian Healthcare/2026/Visit-Notes/2026-04-20_sutter-post-op/
"""
from __future__ import annotations

import json
import logging
import os
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path

import config

logger = logging.getLogger(__name__)


# ── Document type → folder name mapping ────────────────────────────────────────

_DOC_TYPE_FOLDER = {
    "medical_portal_screenshot": "Portal-Screenshots",
    "medical_form": "Forms",
    "insurance_eob": "Insurance-EOB",
    "insurance_document": "Insurance",
    "prescription": "Prescriptions",
    "lab_results": "Lab-Results",
    "receipt": "Receipts",
    "invoice": "Invoices",
    "tax_form": "Tax-Documents",
    "bank_statement": "Bank-Statements",
    "contract": "Contracts",
    "id_card": "ID-Cards",
    "recipe": "Recipes",
    "photo": "Photos",
    "home_improvement": "Projects",
    "mortgage_document": "Mortgage",
    "utility_bill": "Utilities",
}


def _doc_type_to_folder(doc_type: str) -> str:
    """Map a document_type string to a clean folder name.

    Uses the lookup table first, then falls back to title-casing the raw type.
    """
    if not doc_type:
        return "General"
    mapped = _DOC_TYPE_FOLDER.get(doc_type.lower().strip())
    if mapped:
        return mapped
    # Fallback: "appointment_confirmation" → "Appointment-Confirmation"
    return "-".join(
        word.capitalize() for word in doc_type.replace("_", " ").split()
    ) or "General"


def _staging_root() -> Path:
    return Path(config.LOCAL_STAGING_DIR).expanduser()


def _slugify(text: str, max_len: int = 60) -> str:
    """Convert a title to a filesystem-safe slug."""
    slug = text.lower().strip()
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)
    slug = re.sub(r"[\s]+", "-", slug).strip("-")
    return slug[:max_len] or "untitled"


def _nas_available() -> bool:
    """Check if the NAS root directory is accessible."""
    nas_root = Path(config.NAS_ROOT)
    return nas_root.exists() and nas_root.is_dir()


def _build_nas_path(result) -> Path:
    """Build the target NAS directory path from a FileAnalysisResult.

    Structure: {NAS_ROOT}/{category}/{subcategory}/{year}/{doc_type}/{date}_{slug}/
    """
    from models import FileAnalysisResult
    assert isinstance(result, FileAnalysisResult)

    category = result.primary_category
    subcategory = result.subcategory
    date_str = result.date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    year = date_str[:4]
    doc_type_folder = _doc_type_to_folder(getattr(result, "document_type", ""))
    slug = _slugify(result.title)

    if subcategory:
        base = Path(config.NAS_ROOT) / category / subcategory / year / doc_type_folder
    else:
        base = Path(config.NAS_ROOT) / category / year / doc_type_folder

    dirname = f"{date_str}_{slug}"
    target = base / dirname

    # Avoid collisions
    if target.exists():
        for i in range(2, 100):
            candidate = base / f"{dirname}-{i}"
            if not candidate.exists():
                target = candidate
                break

    return target


def _generate_pdf(text: str, title: str, date: str | None, output_path: Path) -> None:
    """Generate a simple PDF from extracted text using reportlab."""
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.units import inch
    from reportlab.pdfgen import canvas

    c = canvas.Canvas(str(output_path), pagesize=letter)
    width, height = letter
    margin = inch
    usable_width = width - 2 * margin

    # Header
    c.setFont("Courier-Bold", 12)
    header = title[:80]
    if date:
        header += f"  |  {date}"
    c.drawString(margin, height - margin, header)
    c.setFont("Courier", 9)
    c.drawString(margin, height - margin - 14, f"Generated by event-aggregator intake pipeline")

    # Body text
    c.setFont("Courier", 10)
    y = height - margin - 40
    line_height = 12
    max_chars = int(usable_width / 6)  # approximate chars per line at 10pt Courier

    for line in text.splitlines():
        # Wrap long lines
        while len(line) > max_chars:
            c.drawString(margin, y, line[:max_chars])
            line = line[max_chars:]
            y -= line_height
            if y < margin:
                c.showPage()
                c.setFont("Courier", 10)
                y = height - margin

        c.drawString(margin, y, line)
        y -= line_height
        if y < margin:
            c.showPage()
            c.setFont("Courier", 10)
            y = height - margin

    c.save()


def _write_summary(result, staging_dir: Path) -> None:
    """Write a human-readable summary.txt alongside the staged files."""
    from models import FileAnalysisResult
    assert isinstance(result, FileAnalysisResult)

    category_display = result.primary_category
    if result.subcategory:
        category_display += f" / {result.subcategory}"

    lines = [
        f"Title: {result.title}",
        f"Date: {result.date or 'unknown'}",
        f"Category: {category_display}",
        f"Document Type: {getattr(result, 'document_type', '') or 'unclassified'}",
        f"Confidence: {result.confidence:.2f}",
        f"Source: Slack file upload ({result.file_id})",
        f"Original filename: {result.original_filename or 'unknown'}",
        "",
        f"Summary: {result.summary}",
    ]
    summary_path = staging_dir / "summary.txt"
    summary_path.write_text("\n".join(lines), encoding="utf-8")


def stage_locally(result, file_bytes: bytes, original_ext: str) -> str:
    """Write original file + extraction.txt + extraction.pdf + summary.txt to local staging.

    Returns the staging directory path as a string.
    """
    from models import FileAnalysisResult
    assert isinstance(result, FileAnalysisResult)

    staging_dir = _staging_root() / result.file_id
    staging_dir.mkdir(parents=True, exist_ok=True)

    # Save original file with descriptive name
    file_slug = _slugify(result.title, max_len=40) or "original"
    original_path = staging_dir / f"{file_slug}{original_ext}"
    original_path.write_bytes(file_bytes)

    # Save extraction text
    txt_path = staging_dir / "extraction.txt"
    txt_path.write_text(result.structured_text, encoding="utf-8")

    # Save extraction PDF
    pdf_path = staging_dir / "extraction.pdf"
    try:
        _generate_pdf(result.structured_text, result.title, result.date, pdf_path)
    except Exception as exc:
        logger.warning("PDF generation failed for %s: %s", result.file_id, exc)

    # Save summary
    _write_summary(result, staging_dir)

    # Save metadata for flush_pending_staged to reconstruct the NAS path
    meta = {
        "file_id": result.file_id,
        "primary_category": result.primary_category,
        "subcategory": result.subcategory,
        "title": result.title,
        "date": result.date,
        "document_type": getattr(result, "document_type", ""),
        "summary": result.summary,
        "original_filename": result.original_filename,
        "staged_at": datetime.now(timezone.utc).isoformat(),
    }
    meta_path = staging_dir / "_metadata.json"
    meta_path.write_text(json.dumps(meta, indent=2), encoding="utf-8")

    logger.info("Staged %s → %s", result.file_id, staging_dir)
    return str(staging_dir)


def stage_document_locally(
    result,
    pages: list[tuple[bytes, str, str]],
    staging_id: str,
) -> str:
    """Stage a multi-page document to local intake folder.

    Creates one folder with descriptively-named page files, plus
    extraction.txt, extraction.pdf, summary.txt, and _metadata.json.

    Args:
        result: FileAnalysisResult for the complete document
        pages: list of (file_bytes, filename, mimetype) in page order
        staging_id: unique ID for the staging dir (e.g. thread_... or msg_ts)

    Returns the staging directory path as a string.
    """
    from models import FileAnalysisResult
    assert isinstance(result, FileAnalysisResult)

    staging_dir = _staging_root() / staging_id
    staging_dir.mkdir(parents=True, exist_ok=True)

    # Save each page with descriptive name + zero-padded numbering
    file_slug = _slugify(result.title, max_len=40) or "page"
    for i, (file_bytes, filename, mimetype) in enumerate(pages, 1):
        ext = Path(filename).suffix or _ext_from_mimetype(mimetype)
        page_path = staging_dir / f"{file_slug}_page{i:02d}{ext}"
        page_path.write_bytes(file_bytes)

    # Save extraction text
    txt_path = staging_dir / "extraction.txt"
    txt_path.write_text(result.structured_text, encoding="utf-8")

    # Save extraction PDF
    pdf_path = staging_dir / "extraction.pdf"
    try:
        _generate_pdf(result.structured_text, result.title, result.date, pdf_path)
    except Exception as exc:
        logger.warning("PDF generation failed for %s: %s", staging_id, exc)

    # Save summary
    _write_summary(result, staging_dir)

    # Save metadata
    meta = {
        "file_id": result.file_id,
        "staging_id": staging_id,
        "primary_category": result.primary_category,
        "subcategory": result.subcategory,
        "title": result.title,
        "date": result.date,
        "document_type": getattr(result, "document_type", ""),
        "summary": result.summary,
        "original_filename": result.original_filename,
        "page_count": len(pages),
        "staged_at": datetime.now(timezone.utc).isoformat(),
    }
    meta_path = staging_dir / "_metadata.json"
    meta_path.write_text(json.dumps(meta, indent=2), encoding="utf-8")

    logger.info("Staged %d-page document %s → %s", len(pages), staging_id, staging_dir)
    return str(staging_dir)


def _ext_from_mimetype(mimetype: str) -> str:
    mapping = {
        "image/png": ".png", "image/jpeg": ".jpg", "image/jpg": ".jpg",
        "image/gif": ".gif", "image/webp": ".webp", "image/heic": ".heic",
        "image/heif": ".heif", "image/tiff": ".tiff", "application/pdf": ".pdf",
    }
    return mapping.get(mimetype, ".bin")


def copy_to_nas(staging_path: str, result, dry_run: bool = False) -> str | None:
    """Copy staged files to the NAS. Returns NAS path on success, None if unavailable.

    Does NOT purge local staging — caller does that after confirming success.
    """
    from models import FileAnalysisResult
    assert isinstance(result, FileAnalysisResult)

    if not _nas_available():
        logger.info("NAS not available at %s — files remain staged at %s", config.NAS_ROOT, staging_path)
        return None

    nas_path = _build_nas_path(result)

    if dry_run:
        logger.info("DRY RUN: would copy %s → %s", staging_path, nas_path)
        return str(nas_path)

    try:
        nas_path.mkdir(parents=True, exist_ok=True)
        staging = Path(staging_path)

        for item in staging.iterdir():
            if item.name == "_metadata.json":
                continue  # internal metadata, don't copy to NAS
            dest = nas_path / item.name
            shutil.copy2(str(item), str(dest))

        logger.info("Copied to NAS: %s → %s", staging_path, nas_path)
        return str(nas_path)

    except Exception as exc:
        logger.warning("Failed to copy to NAS %s: %s", nas_path, exc)
        return None


def purge_staging(staging_path: str) -> None:
    """Remove a local staging directory after successful NAS write."""
    try:
        shutil.rmtree(staging_path)
        logger.debug("Purged staging: %s", staging_path)
    except Exception as exc:
        logger.warning("Failed to purge staging %s: %s", staging_path, exc)


def flush_pending_staged(dry_run: bool = False) -> list[tuple[str, str]]:
    """Attempt to copy any leftover staged files to NAS.

    Called at the start of each run to clear backlog from prior NAS-offline runs.
    Returns list of (file_id, nas_path) pairs that were successfully flushed.
    """
    root = _staging_root()
    if not root.exists():
        return []

    if not _nas_available():
        pending = list(root.iterdir())
        if pending:
            logger.info("NAS still offline — %d staged file(s) waiting", len(pending))
        return []

    flushed = []
    for staged_dir in root.iterdir():
        if not staged_dir.is_dir():
            continue

        meta_path = staged_dir / "_metadata.json"
        if not meta_path.exists():
            logger.debug("Skipping staged dir without metadata: %s", staged_dir)
            continue

        try:
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as exc:
            logger.warning("Bad metadata in %s: %s", staged_dir, exc)
            continue

        # Reconstruct a minimal FileAnalysisResult for _build_nas_path
        from models import FileAnalysisResult
        result = FileAnalysisResult(
            file_id=meta["file_id"],
            primary_category=meta["primary_category"],
            subcategory=meta.get("subcategory"),
            confidence=0.0,
            title=meta["title"],
            date=meta.get("date"),
            structured_text="",
            summary=meta.get("summary", ""),
            document_type=meta.get("document_type", ""),
            original_filename=meta.get("original_filename", ""),
        )

        nas_path = copy_to_nas(str(staged_dir), result, dry_run=dry_run)
        if nas_path:
            if not dry_run:
                purge_staging(str(staged_dir))
            flushed.append((meta["file_id"], nas_path))
            logger.info("Flushed staged file %s → %s", meta["file_id"], nas_path)

    return flushed
